# Generated by Django 5.2 on 2025-04-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Администраторы', 'verbose_name_plural': 'Администрация'},
        ),
    ]
