# Generated by Django 5.2 on 2025-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='Баннер карточки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employees/', verbose_name='Фото сотрудника'),
        ),
    ]
