# Generated by Django 5.2 on 2025-04-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Сотрудники',
        ),
    ]
