# Generated by Django 5.2 on 2025-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
