# Generated by Django 5.2 on 2025-04-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Сотрудники',
        ),
    ]
