# Generated by Django 5.2 on 2025-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='banner',
            field=models.ImageField(blank=True, upload_to='not_banners/', verbose_name='Баннер карточки'),
        ),
    ]
