# Generated by Django 5.2 on 2025-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_employee_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='banner',
            field=models.ImageField(blank=True, upload_to='doNot_url/', verbose_name='Баннер карточки'),
        ),
    ]
