# Generated by Django 5.2 on 2025-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_employee_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='banner',
            field=models.ImageField(blank=True, upload_to='doNot/', verbose_name='Баннер карточки'),
        ),
    ]
