# Generated by Django 5.2 on 2025-04-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_employee_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='banner',
            new_name='doNot',
        ),
    ]
