# Generated by Django 5.2 on 2025-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_rename_banner_employee_donot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='doNot',
        ),
        migrations.AddField(
            model_name='employee',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='Баннер карточки'),
        ),
    ]
