# Generated by Django 5.2 on 2025-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_employee_donot_employee_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='banner',
        ),
        migrations.AddField(
            model_name='employee',
            name='thisnot',
            field=models.ImageField(blank=True, upload_to='thisnot/', verbose_name='Баннер сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Статус'),
        ),
    ]
