# Generated by Django 5.2 on 2025-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_remove_employee_banner_employee_thisnot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='thisnot',
        ),
        migrations.AddField(
            model_name='employee',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='Баннер карточки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
    ]
