# Generated by Django 5.2 on 2025-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_employee_thisnot_employee_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='banner',
        ),
        migrations.AddField(
            model_name='employee',
            name='this',
            field=models.ImageField(blank=True, upload_to='thisnot/', verbose_name='Баннер карточки'),
        ),
    ]
